# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_source/custom_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.main_dialog_frame = QtWidgets.QFrame(Dialog)
        self.main_dialog_frame.setGeometry(QtCore.QRect(200, 50, 300, 400))
        self.main_dialog_frame.setStyleSheet("QFrame {\n"
"    color: whitel;\n"
"    background-color: rgb(23, 23, 23);\n"
"    border-radius: 7px;\n"
"}")
        self.main_dialog_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_dialog_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_dialog_frame.setObjectName("main_dialog_frame")
        self.dialog_label = QtWidgets.QLabel(self.main_dialog_frame)
        self.dialog_label.setGeometry(QtCore.QRect(20, 40, 259, 31))
        self.dialog_label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dialog_label.setFont(font)
        self.dialog_label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.dialog_label.setObjectName("dialog_label")
        self.exit_dialog = QtWidgets.QPushButton(self.main_dialog_frame)
        self.exit_dialog.setGeometry(QtCore.QRect(280, 8, 14, 14))
        self.exit_dialog.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 40, 54);\n"
"    border-radius: 7px;\n"
"    border: none\n"
"}")
        self.exit_dialog.setText("")
        self.exit_dialog.setCheckable(False)
        self.exit_dialog.setDefault(False)
        self.exit_dialog.setFlat(False)
        self.exit_dialog.setObjectName("exit_dialog")
        self.scrollArea = QtWidgets.QScrollArea(self.main_dialog_frame)
        self.scrollArea.setGeometry(QtCore.QRect(20, 80, 259, 299))
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
"            border: 0px solid #999999;\n"
"        \n"
"        background-color: rgb(61, 61, 70);\n"
"            width:8px;    \n"
"            margin: 0px 0px 0px 0px;\n"
"        }\n"
"        QScrollBar::handle:vertical {         \n"
"       \n"
"            min-height: 10px;\n"
"              border: 0px solid red;\n"
"            border-radius: 4px;\n"
"    \n"
"    background-color: rgb(50, 50, 50);\n"
"        }\n"
"        QScrollBar::add-line:vertical {       \n"
"            height: 0px;\n"
"            subcontrol-position: bottom;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::sub-line:vertical {\n"
"            height: 0 px;\n"
"            subcontrol-position: top;\n"
"            subcontrol-origin: margin;\n"
"        }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.dialog_scroll_content = QtWidgets.QWidget()
        self.dialog_scroll_content.setGeometry(QtCore.QRect(0, 0, 259, 299))
        self.dialog_scroll_content.setStyleSheet("QWidgets {\n"
"    background-color: rgb(49, 49, 49);\n"
"}")
        self.dialog_scroll_content.setObjectName("dialog_scroll_content")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.dialog_scroll_content)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 231, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.dialog_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.dialog_layout.setContentsMargins(0, 0, 0, 0)
        self.dialog_layout.setSpacing(3)
        self.dialog_layout.setObjectName("dialog_layout")
        self.scrollArea.setWidget(self.dialog_scroll_content)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dialog_label.setText(_translate("Dialog", "did you mean"))
