# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_source/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_entryWindow(object):
    def setupUi(self, entryWindow):
        entryWindow.setObjectName("entryWindow")
        entryWindow.resize(680, 400)
        self.centralwidget = QtWidgets.QWidget(entryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dropFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dropFrame.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(29, 29, 33);\n"
"    color: rgb(255, 94, 130);\n"
"    border-radius: 10px;\n"
"}")
        self.dropFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropFrame.setObjectName("dropFrame")
        self.name = QtWidgets.QLabel(self.dropFrame)
        self.name.setGeometry(QtCore.QRect(0, 110, 661, 61))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.name.setFont(font)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.description = QtWidgets.QLabel(self.dropFrame)
        self.description.setGeometry(QtCore.QRect(0, 190, 661, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.description.setFont(font)
        self.description.setStyleSheet("QLabel{\n"
"    color: rgb(155, 99, 123);\n"
"}")
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setObjectName("description")
        self.pb1 = QtWidgets.QProgressBar(self.dropFrame)
        self.pb1.setEnabled(False)
        self.pb1.setGeometry(QtCore.QRect(130, 270, 411, 21))
        self.pb1.setStyleSheet("QProgressBar {\n"
"    background-color: rgb(255, 136, 187);\n"
"    color: rgb(200,200,200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-alignment: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.108374, y1:0.426136, x2:0.906, y2:0.403, stop:0 rgba(186, 96, 113, 255), stop:1 rgba(196, 71, 99, 255));\n"
"}")
        self.pb1.setProperty("value", 0)
        self.pb1.setAlignment(QtCore.Qt.AlignCenter)
        self.pb1.setTextVisible(True)
        self.pb1.setInvertedAppearance(False)
        self.pb1.setObjectName("pb1")
        self.triggerButton = QtWidgets.QPushButton(self.dropFrame)
        self.triggerButton.setGeometry(QtCore.QRect(290, 266, 91, 31))
        self.triggerButton.setObjectName("triggerButton")
        self.exitButton = QtWidgets.QPushButton(self.dropFrame)
        self.exitButton.setGeometry(QtCore.QRect(640, 5, 14, 14))
        self.exitButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 40, 54);\n"
"    border-radius: 7px;\n"
"    border: none\n"
"}")
        self.exitButton.setCheckable(False)
        self.exitButton.setDefault(False)
        self.exitButton.setFlat(False)
        self.exitButton.setObjectName("exitButton")
        self.description.raise_()
        self.name.raise_()
        self.exitButton.raise_()
        self.pb1.raise_()
        self.triggerButton.raise_()
        self.horizontalLayout.addWidget(self.dropFrame)
        entryWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(entryWindow)
        QtCore.QMetaObject.connectSlotsByName(entryWindow)

    def retranslateUi(self, entryWindow):
        _translate = QtCore.QCoreApplication.translate
        entryWindow.setWindowTitle(_translate("entryWindow", "MainWindow"))
        self.name.setText(_translate("entryWindow", "<html><head/><body><p><span style=\" font-weight:700;\">asystent 0.1</span></p></body></html>"))
        self.description.setText(_translate("entryWindow", "open"))
        self.triggerButton.setText(_translate("entryWindow", "yea"))
        self.exitButton.setText(_translate("entryWindow", "X"))
